name: Conditions workflow
on: push
jobs:
  skip-or-run:
    if: ${{ github.actor == 'magurotaisa' }} # octocatアカウント以外は実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
  skip:
    if: ${{ github.actor == 'magurotaida' }} # octocatアカウント以外は実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"